### PR TITLE
Cleanup old web3

### PR DESCRIPTION
**Pull request by 1saf**
# Description
Now that the web3 refactor is complete, we should fix up all the naming and any remaining dangling references. This PR removes the web3 vuex module and the old composable files. Also cleaned up any dangling references to the old code.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Other

## How should this be tested?

Just give a general sense check to the app. Only names have changed here, and files.

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code where relevant, particularly in hard-to-understand areas
- [X] My changes generate no new console warnings
- [X] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Review by garethfuller — CHANGES_REQUESTED** [review]
Thanks for this! Couple of things still need to be done I think:

- Do a code search for `.web3` and you'll see that there are still some references to the web3 vuex module.
- Also, the `account` vuex module relies on it quite a lot, can we get rid of that yet?
- Can we get rid of `components/modals/AccountModal.vue`?
- Can we get rid of `constants/connectors.json`?
- Can we get rid of `plugins/authOptions.ts` and all the images imported in that file?

**Comment by 1saf** [comment]
> Thanks for this! Couple of things still need to be done I think:
> 
> * Do a code search for `.web3` and you'll see that there are still some references to the web3 vuex module.
> * Also, the `account` vuex module relies on it quite a lot, can we get rid of that yet?
> * Can we get rid of `components/modals/AccountModal.vue`?
> * Can we get rid of `constants/connectors.json`?
> * Can we get rid of `plugins/authOptions.ts` and all the images imported in that file?

`authOptions.ts` is actually used for logos and names
`connectors.json` is kill
`AccountModal` is kill
`account.ts` is kill

**Review by garethfuller — COMMENTED** [review]
@1saf If we're still using the functions in authOptions to get the logos I think we should probably refactor that so it's part of the web3 service right?

**Comment by 1saf** [comment]
All resolved @garethfuller

**Review by garethfuller — APPROVED** [review]

**Pull request merged**
