### PR TITLE
Scale claims by their token decimal places

### PR DESCRIPTION
**Pull request by gtaschuk**
# Description

This scales token claim balances by the token's decimal places to enable using tokens (like NOTE) with nonstandard token decimal places

Fixes # (issue)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Claiming NOTE should work now
- [ ] Claiming on all networks should work

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code where relevant, particularly in hard-to-understand areas
- [X] My changes generate no new console warnings
- [X] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Review by garethfuller — COMMENTED** [review]
Hey, thanks for putting this together @gtaschuk. I'm just wondering if it might make more sense to update the schema in [MultiTokenClaim.json](https://github.com/balancer-labs/frontend-v2/blob/develop/src/services/claim/MultiTokenClaim.json) to include a decimals attribute for each token?

**Comment by gtaschuk** [comment]
> Hey, thanks for putting this together @gtaschuk. I'm just wondering if it might make more sense to update the schema in [MultiTokenClaim.json](https://github.com/balancer-labs/frontend-v2/blob/develop/src/services/claim/MultiTokenClaim.json) to include a decimals attribute for each token?

I considered that, but found it pretty redundant to add decimals to every `week[network][week][token]` so instead specified it in a new file as `decimals[network][token]`.

What do you think?

**Comment by garethfuller** [comment]
@gtaschuk yeah agree with your logic there.

**Review by garethfuller — COMMENTED** [review]
Just pushed a lint fix, hope you don't mind. I tried to trigger a claim on Mainnet and I'm getting this error:
Screenshot 2021-11-29 at 20 52 15

**Comment by gtaschuk** [comment]
Thanks for the lint fix!

Dang.  Looks like toString() returns exponentiation notation 1.234 x 10^6 by default, so I added an argument that should force normal notation ie 1234000.  I'll retest once it deploys!

**Pull request merged**
