### PR TITLE
Add pool details table

### PR DESCRIPTION
**Pull request by alter-eggo**
# Description

At the bottom of the Pool page, underneath the 'Trades' section was added a new section for Pool attributes

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [x] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Comment by Matthews3301** [comment]
Perhaps it would be possible to make the table more responsive on small screens? At certain breakpoint the row title to be above the value. Also truncating addresses.

**Comment by alter-eggo** [comment]
good catch! thank you

**Review by pkattera — APPROVED** [review]
Looks good to me!

**Comment by garethfuller** [comment]
@pkattera I'd suggest we don't need the 'Pool attributes' title above the table, it seems like a redundant title and the table is self-evident.

Screenshot 2022-09-09 at 14 20 02

**Comment by pkattera** [comment]
> @pkattera I'd suggest we don't need the 'Pool attributes' title above the table, it seems like a redundant title and the table is self-evident.

Agree. Removed.

**Pull request merged**
