### PR TITLE
feat: add trade amount for direct trade linking

### LINKED ISSUE #1994: Add trade amount for direct trade linking
**Is your feature request related to a problem? Please describe.**
Right now it is possible to directly link a trade pair on balancer using the following link format
https://app.balancer.fi/#/trade/[tokenin]/[tokenout]
https://app.balancer.fi/#/trade/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB

**Describe the solution you'd like**
I would like to be able to encode either the input/output amount in the url
i.e.
https://app.balancer.fi/#/trade/[tokenin]/[tokenout]/[0 or 1 for setting input or output]/[quantity]

**Additional context**
This sort of functionality has been requested by partners.  Figured i'd throw the idea out there

### PR DESCRIPTION
**Pull request by findtoni**
# Description

Closes #1994 

- Adds trade input amount for direct trade linking

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?
https://app.balancer.fi/#/trade/[tokenIn]/[tokenOut]/?inAmount=[tokenInAmount]
https://app.balancer.fi/#/trade/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB/?inAmount=25

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [n/a] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Comment by findtoni** [comment]
Kindly review @garethfuller @timjrobinson

**Review by garethfuller — CHANGES_REQUESTED** [review]
Hey @findtoni thanks for looking into this. Although using URL structure was suggested in the issue, I'd rather see this solved with URL params.

https://app.balancer.fi/#/trade/[tokenin]/[tokenout]&inAmount=25
or
https://app.balancer.fi/#/trade/[tokenin]/[tokenout]&outAmount=25

**Comment by findtoni** [comment]
Hi @garethfuller thanks for the review, fixed now. Can you help reopen this? I only have the option to open a new one.

**Comment by findtoni** [comment]
> Hey @findtoni thanks for looking into this. Although using URL structure was suggested in the issue, I'd rather see this solved with URL params.
> 
> [https://app.balancer.fi/#/trade/[tokenin]/[tokenout]&inAmount=25](https://app.balancer.fi/#/trade/%5Btokenin%5D/%5Btokenout%5D&inAmount=25) or [https://app.balancer.fi/#/trade/[tokenin]/[tokenout]&outAmount=25](https://app.balancer.fi/#/trade/%5Btokenin%5D/%5Btokenout%5D&outAmount=25)

It's now
https://app.balancer.fi/#/trade/[tokenin]/[tokenout]?inAmount=25 or
https://app.balancer.fi/#/trade/[tokenin]/[tokenout]?outAmount=25

**Review by garethfuller — CHANGES_REQUESTED** [review]
`outAmount` doesn't seem to work. I tried this on mainnet: `/trade/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB?outAmount=25`

**Comment by findtoni** [comment]
> `outAmount` doesn't seem to work. I tried this on mainnet: `/trade/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB?outAmount=25`

@garethfuller fixed now

**Review by garethfuller — APPROVED** [review]
Working well now, thanks for your work here! 🙌

**Pull request merged**
