### PR TITLE
Improved veBAL voting UX

### PR DESCRIPTION
**Pull request by pkattera**
# Description

General UI/UX improvements to the veBAL voting flow:

- Removes option to extend an already expired lock (as per [Tom's feedback](https://github.com/balancer-labs/frontend-v2/issues/1795#issuecomment-1155645320))
- Distinguishes warnings from errors in the Voting UI
- UI improvements for the voting modal
- New text in voting modal outlining that users need to revote if they get new veBAL
- Better hover states within the locking flow.
- Added in future friendly name support into the voting modal. 
  - Shows the friendly name by default, with the pool symbol name as a backup.  
- Improved tooltip copy

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [x] Other: UI/UX improvements

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Can mostly do a visual check on different browsers for the UI improvements
- [ ] For the expired pools issue, you'll need to use a wallet address with an expired lock. 

## Visual context

voting-ux

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [x] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Comment by timjrobinson** [comment]
@pkattera I simplified the errors/warnings so they are two separate things rather than being warnings and critical warnings to make them easier to understand. I also fixed the bug with the input text being disabled if you enter more than remaining votes. 

The design changes LGTM and the UI works for me. If the UI works well for you we can merge this.

**Comment by pkattera** [comment]
@timjrobinson Thanks for fixing the input bug. Just tested it and it all works for me.

**Review by sssmi — APPROVED** [review]

**Comment by timjrobinson** [comment]
@pkattera I just merged in devel to fix the merge conflict. The only change that was cut in the conflict is you added the class `dark:hover:text-white` to the vote button. Is this still needed? It seems the text on the vote button is white when hovering in dark mode.

**Comment by pkattera** [comment]
@timjrobinson This is looking good on beta.balaner.fi – so it looks like that dark mode button bug got fixed already. Thanks.

**Pull request merged**
