### PR TITLE
use the decentralized graph endpoint

### PR DESCRIPTION
**Pull request by gtaschuk**
# Description

This uses the decentralized graph as the subgraph endpoint

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

- [ ] Verify data flows from graphql

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Comment by markusbkoch** [comment]
@gtaschuk I'm getting `{"errors":{"message":"Invalid query"}}` on all requests to the decentralized subgraph on the mainnet vercel preview deployed in this PR

**Comment by gtaschuk** [comment]
@markusbkoch ah, sorry I asked Gareth about this but string interpolation on putting the api into the URL is failing and he was going to take a quick look at that

**Comment by markusbkoch** [comment]
@gtaschuk still seeing the same erro in the most recent preview deployments. The URL seems to be correct - maybe something about the graphql syntax that the hosted service supports but the network doesn't?

**Comment by mikemcdonald** [comment]
The gateway service enforces strict graphql query validation and the hosted does not. For some reason the app was stringifying the JSON query which caused issues. I pushed a fix, worth double checking all of the various subgraph queries outside the pool list home page

**Comment by timjrobinson** [comment]
I merged latest develop and fixed a bug where the pools table wasn't showing a loading state. 

The decentralised endpoint is slightly slower for initial request (around 400ms wait time for me) which is why I noticed the pools table had a bug where it was saying "no pools" instead of the loading animation while it was loading from the graph. 

All queries seem to be working correctly.

**Review by timjrobinson — APPROVED** [review]

**Comment by markusbkoch** [comment]
Thanks Tim, I just noticed we hadn't applied the latest hotfix to the graph network deployment, that's why I added the `on hold` label. Will report back as soon as the new deployment is live.

**Comment by timjrobinson** [comment]
We reset the `develop` branch to master which confused Github, so I've done a rebase of this branch onto the new develop and force pushed it back. All code changes should be the same.

**Comment by markusbkoch** [comment]
@timjrobinson I've checked the previews and it all looks good. Feel free to merge any time.

**Pull request merged**
