### PR TITLE
Hotfix: ComposableStable join/exit fixes

### PR DESCRIPTION
**Pull request by garethfuller**
# Description

Uses queryJoin and queryExit for shallow ComposableStable pools to override JS math values that are inaccurate because of cached priceRates.

Note: Does not fix ComposableStable proportional exits, this will come in a future PR.

Fixes: #2272

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Shallow ComposableStable pools for testing:
- Goerli - https://beta-goerli-git-hotix-proportional-composable-stable-balancer.vercel.app/#/pool/0x98087bf6a5ca828a6e09391ace674dbabb6a4c5600000000000000000000019b
- Polygon - https://beta-polygon-git-hotix-proportional-composable-stable-balancer.vercel.app/#/pool/0x8159462d255c1d24915cb51ec361f700174cd99400000000000000000000075d
- Polygon - https://beta-polygon-git-hotix-proportional-composable-stable-balancer.vercel.app/#/pool/0xb20fc01d21a50d2c734c4a1262b4404d41fa7bf000000000000000000000075c

Things to test:
- [ ] Test maximum proportional exit from ComposableStable pool. Check dust amount is reasonable.
- [ ] Test partial proportional exit from ComposableStable pool.
- [ ] Test proportional exits from non ComposableStable pools.

## Visual context

n/a

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [x] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Review by alter-eggo — APPROVED** [review]
lgtm + successfully tested polygon withdrawals

**Review by timjrobinson — APPROVED** [review]
Tested Goerli withdrawing 54% proportionally and then 80% of just one token and it worked.

**Comment by timjrobinson** [comment]
I'm able to invest, stake, unstake, withdraw from the new MATIC/MATICx pool after the latest changes. 

After I invested + staked the pool page did look strange for a moment:
2022-09-30-151355_545x678_scrot

But then it updated about 10 seconds later and was correct - I guess slow graph updates? 

2022-09-30-151421_531x641_scrot

**Comment by timjrobinson** [comment]
I got an error withdrawing single token MaticX, but all other withdraw types worked (Proportional 30%, 0.3 wMATIC, 0.3 MATIC all worked)

2022-09-30-151932_543x520_scrot

**Pull request merged**
