### PR TITLE
Convert pool id param to lowercase

### LINKED ISSUE #2229: Handle uppercase pool ids in the URL
**Describe the bug**
Some elements in the pool page are not displayed if the pool ID in the URL is uppercased
https://app.balancer.fi/#/pool/0X7B50775383D3D6F0215A8F290F2C9E2EEBBECEB20000000000000000000000FE

This is because the id is not always lowercased before being passed to some subgraph queries. Example:
image

**To Reproduce**
1. Go to https://app.balancer.fi/#/pool/0X7B50775383D3D6F0215A8F290F2C9E2EEBBECEB20000000000000000000000FE
1. See that stats chart and activity table are missing

**Expected behavior**
Display all pool page elements

### PR DESCRIPTION
**Pull request by garethfuller**
# Description

Fixes #2229

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

- [ ] Test this pool ID `0X7B50775383D3D6F0215A8F290F2C9E2EEBBECEB20000000000000000000000FE` on the mainnet preview. The chart should load.

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [x] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Review by markusbkoch — CHANGES_REQUESTED** [review]
Thanks. Chart looks good, but activity tables still come out empty for me, see eg https://beta-app-git-fix-uppercase-pool-id-balancer.vercel.app/#/pool/0X5C6EE304399DBDB9C8EF030AB642B10820DB8F56000200000000000000000014

**Comment by garethfuller** [comment]
@markusbkoch should be fixed now.

**Comment by markusbkoch** [comment]
looks good, but I'm getting this intermitent layout bug now
image

**Review by markusbkoch — APPROVED** [review]
lgtm. thanks

**Pull request merged**
