### PR TITLE
Tailwind v3

### PR DESCRIPTION
**Pull request by insulineru**
# Description

Fixed issue #1770 

More description after finished 👀

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Comment by pkattera** [comment]
Thanks @insulineru for upgrading to Tailwind 3 and updating some of the classes to use the new syntax. I'm a designer and I don't know enough about webpack 5 or if we want to migrate that as well. It's best that @timjrobinson reviews and provides feedback here.

**Comment by timjrobinson** [comment]
Hi @insulineru, is this PR ready for review? It's still in draft mode, please change it to ready to review mode when you're ready.

**Comment by insulineru** [comment]
> Hi @insulineru, is this PR ready for review? It's still in draft mode, please change it to ready to review mode when you're ready.

Hi, @timjrobinson. Thank you for response. I mentioned [above](https://github.com/balancer-labs/frontend-v2/pull/1968#issuecomment-1154963767) that the approximate time frame for a global migration would be about 20 hours. would not want to do this in case there is any reason not to migrate the project to the new webpack.

**Comment by alter-eggo** [comment]
Hey @insulineru, sorry for the long answer. Yes, we need migration to webpack 5. 
Also we want to create two separate pr’s with updating webpack and updating tailwind. In order to be more sure that there won’t be any problems with the ui.

I would like to ask if you are planning to continue working on this issue?

**Comment by insulineru** [comment]
> Hey @insulineru, sorry for the long answer. Yes, we need migration to webpack 5. Also we want to create two separate pr’s with updating webpack and updating tailwind. In order to be more sure that there won’t be any problems with the ui.
> 
> I would like to ask if you are planning to continue working on this issue?

Yes, i can continue, but this branch is not actual. I can create new branch and start migrate to Webpack v5 first. 

imho: Vite is better, than Webpack 👀

**Pull request closed without merging**
