### PR TITLE
feat: Generate TODO file from comments

### PR DESCRIPTION
**Pull request by garethfuller**
# Description

Generates a TODO.md file on every push from TODO comments in code.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

n/a

## Visual context

n/a

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [x] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Comment by garethfuller** [comment]
Not sure if this is a good idea but wanted to test it out in case it was useful so we don't forget parts of the code that need fixed.

**Review by simeonkerkola — APPROVED** [review]
I like it.

**Review by alter-eggo — APPROVED** [review]
nice 👍 easier to understand where we can improve the codebase now

**Review by agualis — COMMENTED** [review]
Can we somehow add a check to limit the max number of TODOs? 
I think it can be useful if we keep the TODO list small to make sure that we frequently address them.

**Comment by garethfuller** [comment]
@agualis Do you have any idea how that could work? Just limit the number injected into the file?

**Comment by simeonkerkola** [comment]
Can the `// TODO` regex be modified so it matches both `// TODO` and `// TODO:`? I think a comment with colon is the more common way.

**Comment by agualis** [comment]
> 
Adding this at the beginning of the generated file and making sure that it is included in eslint:

`/* eslint max-lines: ["error", {"max": 50, "skipBlankLines": true}] */
`

**Comment by garethfuller** [comment]
> > 
> 
> Adding this at the beginning of the generated file and making sure that it is included in eslint:
> 
> `/* eslint max-lines: ["error", {"max": 50, "skipBlankLines": true}] */ `

Not sure if this will achieve what you're looking for, right? It will just cause checks to fail in any PR once you cross that max. Which would force someone to remove TODOs to get a PR to pass checks. In reality devs will probably just delete todos...

**Comment by agualis** [comment]
> Not sure if this will achieve what you're looking for, right? It will just cause checks to fail in any PR once you cross that max. Which would force someone to remove TODOs to get a PR to pass checks. In reality devs will probably just delete todos...

If a dev deletes a TODO then another dev will see it in the PR review. If the TODO was not so important it is ok to delete it. IMO The important think is that it reminds the team to review the TODO list from time to time (if they just add new TODOs but they don't clean old ones).

**Comment by garethfuller** [comment]
> 
> If a dev deletes a TODO then another dev will see it in the PR review. If the TODO was not so important it is ok to delete it. IMO The important think is that it reminds the team to review the TODO list from time to time (if they just add new TODOs but they don't clean old ones).

Ok I guess that might work. I can see us just constantly incrementing the max though to make PRs pass. 😂,

**Comment by garethfuller** [comment]
> Can the `// TODO` regex be modified so it matches both `// TODO` and `// TODO:`? I think a comment with colon is the more common way.

@simeonkerkola agreed, I'll try to improve it so it's more robust before I merge.

**Comment by agualis** [comment]
> Ok I guess that might work. I can see us just constantly incrementing the max though to make PRs pass. 😂,

Like when you enforce 80% testing coverage and devs add tests with empty assertions to hack the metric 😄

I think that it can work if we are a bit disciplined. If not, why having TODOs at all if you are not taking care of them 😇

**Comment by garethfuller** [comment]
Not sure if auto-commits are the best approach here. Closing and will reconsider how to approach this.

**Pull request closed without merging**
