### PR TITLE
Add graviaura pool to allowlist 

### PR DESCRIPTION
**Pull request by Darruma**
# Description

Please include a summary of the change and if relevant which issue is fixed. Please also include relevant motivation and context.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Comment by timjrobinson** [comment]
Could you please add some context of who you talked to at Balancer about this, if there was a snapshot vote, etc.

**Comment by Darruma** [comment]
> Could you please add some context of who you talked to at Balancer about this, if there was a snapshot vote, etc.

Ah, didn't realise there was a voting process for this, I was directed by mendesfabio#9256 to make a pr to allowlist the pool

**Comment by timjrobinson** [comment]
The snapshot vote isn't necessary for a pool whitelist, though it is needed for a gauge. I'd just like more context around who you are, what the pool is, who you talked to about it etc, as otherwise we don't know if this pool is malicious or impersonating another pool etc.

**Comment by Darruma** [comment]
https://badger.com/gravity
https://app.badger.com/vault/aura-graviaura?chain=ethereum

The pool is built in order for users to trade aura for graviaura, which is a vault that we have built as a liquid version of vote locked aura.

**Comment by timjrobinson** [comment]
Thanks for the information. 

Sorry about the confusion with the branches. Yesterday we reset the develop branch to be the same as master because of a divergence in them. Could you make this PR point at master and just include the new pool to be whitelisted and a patch version bump. 

Also in another chat someone mentioned @rabmarut is reviewing this pool currently, so I'm awaiting his approval before adding it.

**Comment by Darruma** [comment]
> Thanks for the information.
> 
> Sorry about the confusion with the branches. Yesterday we reset the develop branch to be the same as master because of a divergence in them. Could you make this PR point at master and just include the new pool to be whitelisted and a patch version bump. It'd probably be easiest to just create a new branch off master with those changes.
> 
> Also in another chat someone mentioned @rabmarut is reviewing this pool currently, so I'm awaiting his approval before adding it.

Ah ok, will make another pr

**Comment by Darruma** [comment]
[Add graviaura pool to allowlist](https://github.com/balancer-labs/frontend-v2/pull/2024)
@rabmarut @timjrobinson

**Pull request closed without merging**
