### PR TITLE
Hotfix: Reduce the number of Tenderly API calls

### PR DESCRIPTION
**Pull request by simeonkerkola**
# Description

Call queryExit and queryJoin less often to reduce the nmbr of calls to Tenderly api

1. When user is changing input amounts queries are debounced, but first query will not fire immediately (`leading` is off)
2. `refetchOnWindowFocus` for queries is disabled, but queries still refetch in the background if Preview Modal is open.
3. Prevent invest form rerender if user tokens array hasn't changed

## Type of change

- [x] Other

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [x] I have commented my code where relevant, particularly in hard-to-understand areas
- [x] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Comment by timjrobinson** [comment]
I'm seeing some weird glitch where numbers keep being reset to 0 after a few seconds (maybe after the simulation returns). It only happens when manually entering and not when clicking max.

**Comment by timjrobinson** [comment]
Looks like the glitch is also happening in prod so may be unrelated. The calls to tenderly have reduced so that part LGTM.

**Comment by timjrobinson** [comment]
Yea it seems to reset all the values on re-focus. Could you look into that, I thought it wouldn't be refetching on focus after this change.

**Comment by simeonkerkola** [comment]
> I'm seeing some weird glitch where numbers keep being reset to 0 after a few seconds (maybe after the simulation returns). It only happens when manually entering and not when clicking max.

Thanks. I noticed it too now.
When wallet balances update, that might cause a rerender. It's not related to this, so I'm going to fix that in a separate PR.

**Review by timjrobinson — APPROVED** [review]
Sounds good. This reduces the calls so LGTM

**Pull request merged**
