### PR TITLE
Migrate to vite 4

### PR DESCRIPTION
**Pull request by agualis**
# Description

[vite 4 was released](https://vitejs.dev/blog/announcing-vite4.html) while we were migrating to vite 3. 

This PR migrates to the last release. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 1 review (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Review by simeonkerkola — APPROVED** [review]

**Review by garethfuller — CHANGES_REQUESTED** [review]
There's a layout bug on pool pages: https://www.loom.com/share/b87fa457565346d384fa59606dfc6fb1

I think it might have something to do with the conditional pool render in pool page header, but not sure.

**Comment by agualis** [comment]
> There's a layout bug on pool pages: https://www.loom.com/share/b87fa457565346d384fa59606dfc6fb1
> 
> I think it might have something to do with the conditional pool render in pool page header, but not sure.

I introduced this regression when updating to the last version of vue. There were some new TS errors because it improves typecheck and I initially added an incomplete fix. 

This is the correct fix.:

We had a `v-if  v-else `showing a `BalLoadingBlock` while the `pool` was being loaded (edited) 

That forced us to check `loadingPool` in some other` v-if` s

Given that we are using this component (`PoolPageHeader`) just once, we could get rid of some code and explicit type checking by:

1. Making the `pool` prop required
2. Moving `BalLoadingBlock`  to the parent level
3. Removing `loadingProp` and related logic as it does not make sense anymore

Here is the commit: https://github.com/balancer-labs/frontend-v2/pull/2701/commits/d7e34db3eda266982a00fad5166cf66532dce6a8

**Review by garethfuller — CHANGES_REQUESTED** [review]
I think there is a custom class `header-loading-block` in PoolPageHeader for the loading box so it's the correct height. Now it has no height. Please copy that class to the pool page.

**Comment by agualis** [comment]
> I think there is a custom class `header-loading-block` in PoolPageHeader for the loading box so it's the correct height. Now it has no height. Please copy that class to the pool page.
🙈 Fixed. I think that it finally works as expected:

screencast 2023-01-25 13-35-05

**Review by garethfuller — APPROVED** [review]

**Pull request merged**
