### PR TITLE
Gauge vote testing

### PR DESCRIPTION
**Pull request by garethfuller**
# Description

This PR is to describe how the gauge voting flow can be tested and to collect feedback.

## How should this be tested?

Pre-condition: To be able to vote you need to have veBAL by locking the BPT of the 80/20 pool.

First navigate to the [veBAL page in the kovan preview URL](https://beta-kovan-git-testing-voting-balancer.vercel.app/#/vebal).

- [ ] Test the /vebal page loads and causes no errors with wallet disconnected
- [ ] Test connecting wallet on page, vebal stats should load, voting buttons should appear.
- [ ] Test voting on gauges by clicking on 'Vote' and completing the flow.

## Visual context

Demo: [https://www.loom.com/share/67271b990989411d9c6b9e3848077772](https://www.loom.com/share/67271b990989411d9c6b9e3848077772)

Screenshot 2022-03-16 at 19 28 21
Screenshot 2022-03-16 at 19 38 47

### CODE REVIEW

**Comment by mikebmikeb** [comment]
The UI should reflect that although a user has veBAL locked, they will need to wait until the following epoch before they are able to vote.  Right now it just throws an nonspecific error when this is the case.

**Comment by markusbkoch** [comment]
If I type an invalid amount the % field is disabled and I have to close the modal before I can type again
image

**Comment by markusbkoch** [comment]
When I click the "vote" button the modal pops up with what looks like a prefilled value, but in reality the field is empty. That information is redundant with the "Your remaining votes" notice aniway, so I think it's best to remove the number from inside the field, or have it actually be a prefilled value
image

**Comment by markusbkoch** [comment]
Is it to be expected that "Current voting period ends:" is empty?
image

**Comment by garethfuller** [comment]
> Is it to be expected that "Current voting period ends:" is empty? image

@markusbkoch this is already fixed, about to merge in now.

**Comment by markusbkoch** [comment]
> @markusbkoch this is already fixed, about to merge in now.

Thanks. After a refresh (before you merged the fix) I saw this. Aren't voting periods supposed to be weekly?
image

**Comment by markusbkoch** [comment]
If the user has no veBAL, I don't think we should say they have 100% unallocated votes. How about we change that to "Get veBAL to vote on liquidity mining allocations"?
image

**Comment by markusbkoch** [comment]
> > @markusbkoch this is already fixed, about to merge in now.
> 
> Thanks. After a refresh (before you merged the fix) I saw this. Aren't voting periods supposed to be weekly? image

Using a different account where the BPT is locked until March 24 I see a different date for the end of the voting period.
image

**Comment by garethfuller** [comment]
> If I type an invalid amount the % field is disabled and I have to close the modal before I can type again image

@markusbkoch this should be fixed.

**Comment by garethfuller** [comment]
> When I click the "vote" button the modal pops up with what looks like a prefilled value, but in reality the field is empty. That information is redundant with the "Your remaining votes" notice aniway, so I think it's best to remove the number from inside the field, or have it actually be a prefilled value image

@markusbkoch this is fixed, I've removed the placeholder and have the input autofocus when the modal is opened.

**Comment by FernandoMartinelli** [comment]
Small improvement but I'd add maybe two quick suggestions for lock durations like "[6 months](url)  |  [1 year](url)" under the date input field, the same way we have "[max](url)" suggestion for the quantity

**Comment by FernandoMartinelli** [comment]
We should change the first two bullets to:
* Earn part of all protocol revenues
* Boost your liquidity mining yield by up to 2.5x

In practice 50% of swap fees for some pools are protocol revenues, out of which 75% is distributed to veBAL holders, the other 25% going to the treasury. There are other sources of revenue other than swap fees, so this is quite complex and hard to put a % here.

image

**Comment by garethfuller** [comment]
> If the user has no veBAL, I don't think we should say they have 100% unallocated votes. How about we change that to "Get veBAL to vote on liquidity mining allocations"? image

This is fixed.

**Comment by garethfuller** [comment]
> > > @markusbkoch this is already fixed, about to merge in now.
> > 
> > 
> > Thanks. After a refresh (before you merged the fix) I saw this. Aren't voting periods supposed to be weekly? image
> 
> Using a different account where the BPT is locked until March 24 I see a different date for the end of the voting period. image

@markusbkoch This should also be fixed now.

**Comment by garethfuller** [comment]
> We should change the first two bullets to:
> 
> * Earn part of all protocol revenues
> * Boost your liquidity mining yield by up to 2.5x
> 
> In practice 50% of swap fees for some pools are protocol revenues, out of which 75% is distributed to veBAL holders, the other 25% going to the treasury. There are other sources of revenue other than swap fees, so this is quite complex and hard to put a % here.
> 
> image

@FernandoMartinelli Done

**Pull request merged**
