### PR TITLE
Add Polygon tetuBAL-80BAL-20WETH stable pool to whitelist.

### PR DESCRIPTION
**Pull request by AlehNat**
# Description

Please include a summary of the change and if relevant which issue is fixed. Please also include relevant motivation and context.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [x] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] pool should be visible at https://polygon.balancer.fi/#/pool/0xb4b22bd6cdad0ab828be6f8a4086dfa54e9b373600020000000000000000058f

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [x] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Review by timjrobinson — APPROVED** [review]
LGTM, can you please rebase on master and bump version again and then we can merge. Also waiting on Markus to check the pool is correct.

**Comment by timjrobinson** [comment]
@AlehNat You can add the token in https://github.com/balancer-labs/assets.

**Comment by markusbkoch** [comment]
> Hello @timjrobinson , thanks for the review. Could you please also give me some hit what should we do to add tetuBal token to the list at balancer swap?

@AlehNat:  https://github.com/balancer-labs/assets#how-to-add-a-token-to-balancer

**Comment by markusbkoch** [comment]
@AlehNat FYI the updated Polygon subgraph capable of handling the new factory is still syncing. At the current rate, it should complete copying data from the previous subgraph in ~20 hours and then it should take a little longer until it's synced the past few days worth of data. We're in touch with Edge&Node trying to speed this up as much as possible, but until it's complete the pool can't be displayed on the UI and trades can't be routed through it.


image

**Review by markusbkoch — APPROVED** [review]
LGTM and subgraph has synced. @timjrobinson can you please rebase if needed when you're ready to merge? Thanks.

**Pull request merged**
