### PR TITLE
Vite tailwind3

### PR DESCRIPTION
**Pull request by agualis**
# Description

Migrate to tailwind 3.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

## Visual context

Please provide any relevant visual context for UI changes or additions. This could be static screenshots or a loom screencast.

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have requested at least 2 reviews (If the PR is significant enough, use best judgement here)
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] If package-lock.json has changes, it was intentional.
- [ ] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Comment by mikemcdonald** [comment]
This may also be a good opportunity to move from node 14 to 16/18 (maybe in a separate PR). When building I got out of memory issues. Can obviously fix using `max_old_space_size`, but running with node 16 also resolved

**Comment by agualis** [comment]
> This may also be a good opportunity to move from node 14 to 16/18 (maybe in a separate PR). When building I got out of memory issues. Can obviously fix using `max_old_space_size`, but running with node 16 also resolved

Note that we already removed the node 14 requirement it in the base branch (`vitest` branch): https://github.com/balancer-labs/frontend-v2/pull/2478/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by pkattera** [comment]
Looks good to me. I've reviewed and fixed the only bug that I could find. There are some differences in font weights, where properties like `font-medium` are used in `@apply` css. This branch treats them correctly, so no need to change anything.

**Review by garethfuller — APPROVED** [review]
@agualis Since this is another long-standing PR could you create a new PR with the diff again, please?

**Pull request closed without merging**
